# Generated by Django 4.2.30 on 2026-04-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': '支付记录', 'verbose_name_plural': '支付记录'},
        ),
        migrations.AlterModelOptions(
            name='paymentevent',
            options={'ordering': ['-processed_at'], 'verbose_name': '支付事件', 'verbose_name_plural': '支付事件'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='approval_url',
            field=models.URLField(blank=True, verbose_name='支付跳转地址'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='checkout_token_or_session_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='会话 / 支付令牌'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_payment_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='第三方支付单号'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='所属订单'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付完成时间'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20, verbose_name='支付渠道'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='原始回调数据'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('requires_action', '待用户操作'), ('paid', '已支付'), ('failed', '支付失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='event_id',
            field=models.CharField(max_length=120, verbose_name='事件 ID'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='event_type',
            field=models.CharField(max_length=120, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='事件数据'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20, verbose_name='支付渠道'),
        ),
    ]
