# Generated by Django 4.2.30 on 2026-04-28 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('payments', '0002_alter_payment_options_alter_paymentevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempts', to='transactions.transaction', verbose_name='所属交易'),
        ),
    ]
