services:
  web:
    build:
      context: .
    container_name: xuanor_site_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
      - media_data:/app/media
    restart: unless-stopped

volumes:
  sqlite_data:
  media_data:
