# Generated by Django 4.2.30 on 2026-04-28 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0003_refund_completed_at_refund_failure_reason_and_more'),
        ('shipping', '0003_shipment_carrier_name_shipment_exception_notes_and_more'),
        ('support_chat', '0002_chatofflinemessage_chatsession_related_order_no'),
        ('orders', '0003_order_closed_at_order_internal_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(blank=True, max_length=32, unique=True, verbose_name='售后单号')),
                ('case_type', models.CharField(choices=[('refund_only', '仅退款'), ('return_refund', '退货退款'), ('resend', '补发'), ('logistics_exception', '物流异常'), ('other', '其他')], default='refund_only', max_length=32, verbose_name='售后类型')),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='售后状态')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='售后原因')),
                ('customer_message', models.TextField(blank=True, verbose_name='客户描述')),
                ('internal_notes', models.TextField(blank=True, verbose_name='内部备注')),
                ('resolution_summary', models.TextField(blank=True, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_cases', to='support_chat.chatsession', verbose_name='关联客服会话')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_cases', to='orders.order', verbose_name='关联订单')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_cases', to='transactions.refund', verbose_name='关联退款')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_cases', to='shipping.shipment', verbose_name='关联发货单')),
            ],
            options={
                'verbose_name': '售后单',
                'verbose_name_plural': '售后单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AfterSalesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40, verbose_name='事件类型')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='事件说明')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='after_sales.aftersalescase', verbose_name='所属售后单')),
            ],
            options={
                'verbose_name': '售后事件',
                'verbose_name_plural': '售后事件',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
