# Generated by Django 4.2.30 on 2026-04-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='联系地址'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='brand_tagline',
            field=models.CharField(blank=True, max_length=200, verbose_name='品牌标语'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='站点图标'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='footer_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='页脚文案'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='icp_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='ICP备案号'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='站点 Logo'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='public_security_beian',
            field=models.CharField(blank=True, max_length=100, verbose_name='公安备案号'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='站点描述'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default='XUANOR', max_length=100, verbose_name='站点名称'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_title',
            field=models.CharField(default='XUANOR | Quiet symbols for modern life', max_length=200, verbose_name='站点标题'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
