# Generated by Django 4.2.30 on 2026-04-18 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(editable=False, max_length=40, unique=True, verbose_name='公开令牌')),
                ('status', models.CharField(choices=[('open', '进行中'), ('waiting_operator', '待客服回复'), ('waiting_visitor', '待访客回复'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='会话状态')),
                ('visitor_name', models.CharField(blank=True, max_length=100, verbose_name='访客姓名')),
                ('visitor_email', models.EmailField(blank=True, max_length=254, verbose_name='访客邮箱')),
                ('visitor_language', models.CharField(default='en', max_length=20, verbose_name='访客语言')),
                ('operator_language', models.CharField(default='zh-hans', max_length=20, verbose_name='客服语言')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
                ('last_seen_by_visitor_at', models.DateTimeField(blank=True, null=True, verbose_name='访客最后查看时间')),
                ('last_seen_by_operator_at', models.DateTimeField(blank=True, null=True, verbose_name='客服最后查看时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('visitor', '访客'), ('operator', '客服'), ('system', '系统')], max_length=20, verbose_name='发送方')),
                ('body_original', models.TextField(verbose_name='原文')),
                ('original_language', models.CharField(max_length=20, verbose_name='原文语言')),
                ('body_for_visitor', models.TextField(verbose_name='面向访客内容')),
                ('body_for_operator', models.TextField(verbose_name='面向客服内容')),
                ('translation_status', models.CharField(choices=[('translated', '已翻译'), ('failed', '翻译失败'), ('not_needed', '无需翻译')], default='not_needed', max_length=20, verbose_name='翻译状态')),
                ('translation_meta', models.JSONField(blank=True, default=dict, verbose_name='翻译元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='客服用户')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_chat.chatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
