# Generated by Django 4.2.30 on 2026-04-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatOfflineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='姓名')),
                ('contact', models.CharField(max_length=255, verbose_name='联系方式')),
                ('related_order_no', models.CharField(blank=True, max_length=32, verbose_name='关联订单号')),
                ('message', models.TextField(verbose_name='留言内容')),
                ('status', models.CharField(choices=[('new', '待处理'), ('done', '已处理')], default='new', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '离线留言',
                'verbose_name_plural': '离线留言',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='related_order_no',
            field=models.CharField(blank=True, max_length=32, verbose_name='关联订单号'),
        ),
    ]
