# Generated by Django 4.2.30 on 2026-04-25 02:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_seo_description_product_seo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveElementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='选项文案')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试选项',
                'verbose_name_plural': '测试选项',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FiveElementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('wood', '木'), ('fire', '火'), ('earth', '土'), ('metal', '金'), ('water', '水')], max_length=10, verbose_name='元素代码')),
                ('name', models.CharField(max_length=40, verbose_name='结果名称')),
                ('theme_word', models.CharField(max_length=40, verbose_name='主题词')),
                ('emotion_title', models.CharField(max_length=160, verbose_name='情绪命名标题')),
                ('emotion_body', models.TextField(verbose_name='情绪命名文案')),
                ('result_title', models.CharField(max_length=160, verbose_name='结果标题')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='短描述')),
                ('long_description', models.TextField(blank=True, verbose_name='长描述')),
                ('primary_symbol_title', models.CharField(max_length=120, verbose_name='主符号标题')),
                ('primary_symbol_description', models.TextField(blank=True, verbose_name='主符号文案')),
                ('ritual_object_title', models.CharField(max_length=120, verbose_name='仪式物标题')),
                ('ritual_object_description', models.TextField(blank=True, verbose_name='仪式物文案')),
                ('ambient_object_title', models.CharField(max_length=120, verbose_name='氛围物标题')),
                ('ambient_object_description', models.TextField(blank=True, verbose_name='氛围物文案')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '五行结果',
                'verbose_name_plural': '五行结果',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FiveElementQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='测试名称')),
                ('slug', models.SlugField(unique=True, verbose_name='访问标识')),
                ('title', models.CharField(max_length=160, verbose_name='前台标题')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='前台副标题')),
                ('intro_title', models.CharField(blank=True, max_length=160, verbose_name='介绍标题')),
                ('intro_body', models.TextField(blank=True, verbose_name='介绍文案')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=3, verbose_name='预计时长（分钟）')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序值')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '五行测试',
                'verbose_name_plural': '五行测试',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FiveElementSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='结果令牌')),
                ('respondent_name', models.CharField(blank=True, max_length=120, verbose_name='姓名')),
                ('respondent_email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('answers_json', models.JSONField(blank=True, default=list, verbose_name='答案快照')),
                ('score_snapshot', models.JSONField(blank=True, default=dict, verbose_name='得分快照')),
                ('utm_source', models.CharField(blank=True, max_length=120, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=120, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=120, verbose_name='UTM Campaign')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('primary_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_submissions', to='pages.fiveelementprofile', verbose_name='主结果')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pages.fiveelementquiz', verbose_name='所属测试')),
                ('secondary_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_submissions', to='pages.fiveelementprofile', verbose_name='次级结果')),
            ],
            options={
                'verbose_name': '测试提交记录',
                'verbose_name_plural': '测试提交记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiveElementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255, verbose_name='题目')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='辅助文案')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pages.fiveelementquiz', verbose_name='所属测试')),
            ],
            options={
                'verbose_name': '测试题目',
                'verbose_name_plural': '测试题目',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FiveElementProfileProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary_symbol', '主符号'), ('ritual_object', '仪式物'), ('ambient_object', '氛围/承接物'), ('backup', '备用推荐')], max_length=20, verbose_name='推荐角色')),
                ('blurb', models.CharField(blank=True, max_length=255, verbose_name='推荐说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='five_element_mappings', to='products.product', verbose_name='关联商品')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='pages.fiveelementprofile', verbose_name='所属结果')),
            ],
            options={
                'verbose_name': '结果推荐商品',
                'verbose_name_plural': '结果推荐商品',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fiveelementprofile',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='pages.fiveelementquiz', verbose_name='所属测试'),
        ),
        migrations.CreateModel(
            name='FiveElementOptionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=1, verbose_name='得分')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='pages.fiveelementoption', verbose_name='所属选项')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_scores', to='pages.fiveelementprofile', verbose_name='结果元素')),
            ],
            options={
                'verbose_name': '选项得分映射',
                'verbose_name_plural': '选项得分映射',
                'ordering': ['-score', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fiveelementoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pages.fiveelementquestion', verbose_name='所属题目'),
        ),
        migrations.AddConstraint(
            model_name='fiveelementprofile',
            constraint=models.UniqueConstraint(fields=('quiz', 'code'), name='unique_five_element_profile_code_per_quiz'),
        ),
        migrations.AddConstraint(
            model_name='fiveelementoptionscore',
            constraint=models.UniqueConstraint(fields=('option', 'profile'), name='unique_five_element_option_profile_score'),
        ),
    ]
