# Generated by Django 4.2.30 on 2026-04-28 00:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
        ('payments', '0002_alter_payment_options_alter_paymentevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='账户编码')),
                ('name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账务账户',
                'verbose_name_plural': '账务账户',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('succeeded', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '对账任务',
                'verbose_name_plural': '对账任务',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('purchase', '购买')], default='purchase', max_length=20, verbose_name='交易类型')),
                ('provider', models.CharField(blank=True, max_length=20, verbose_name='主支付渠道')),
                ('status', models.CharField(choices=[('initiated', '已发起'), ('pending', '待支付'), ('requires_action', '待用户操作'), ('paid', '已支付'), ('failed', '支付失败'), ('cancelled', '已取消')], default='initiated', max_length=20, verbose_name='交易状态')),
                ('risk_status', models.CharField(choices=[('none', '未评估'), ('allow', '放行'), ('review', '人工审核'), ('block', '阻断')], default='none', max_length=20, verbose_name='风控状态')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易金额')),
                ('currency', models.CharField(max_length=3, verbose_name='币种')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '交易',
                'verbose_name_plural': '交易',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('initiated', '交易发起'), ('payment_pending', '待支付'), ('payment_requires_action', '待用户操作'), ('payment_paid', '支付成功'), ('payment_failed', '支付失败'), ('payment_cancelled', '支付取消')], max_length=40, verbose_name='事件类型')),
                ('source', models.CharField(max_length=40, verbose_name='事件来源')),
                ('idempotency_key', models.CharField(max_length=120, verbose_name='幂等键')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_events', to='payments.payment', verbose_name='支付尝试')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='transactions.transaction', verbose_name='所属交易')),
            ],
            options={
                'verbose_name': '交易事件',
                'verbose_name_plural': '交易事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('allow', '放行'), ('review', '人工审核'), ('block', '阻断')], default='allow', max_length=20, verbose_name='决策')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='风险分')),
                ('triggered_rules', models.JSONField(blank=True, default=list, verbose_name='命中规则')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='风险上下文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='transactions.transaction', verbose_name='关联交易')),
            ],
            options={
                'verbose_name': '风控评估',
                'verbose_name_plural': '风控评估',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退款金额')),
                ('currency', models.CharField(max_length=3, verbose_name='币种')),
                ('status', models.CharField(choices=[('requested', '已申请'), ('processing', '处理中'), ('succeeded', '退款成功'), ('failed', '退款失败'), ('cancelled', '已取消')], default='requested', max_length=20, verbose_name='退款状态')),
                ('provider_refund_id', models.CharField(blank=True, max_length=120, verbose_name='第三方退款单号')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='退款原因')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='原始退款数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.payment', verbose_name='原支付')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='transactions.transaction', verbose_name='所属交易')),
            ],
            options={
                'verbose_name': '退款',
                'verbose_name_plural': '退款',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('paid_without_ledger', '支付成功未记账'), ('order_transaction_mismatch', '订单交易状态不一致'), ('amount_mismatch', '金额不一致'), ('duplicate_external_id', '外部单号重复')], max_length=50, verbose_name='异常类型')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='异常详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_items', to='payments.payment', verbose_name='关联支付')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.reconciliationrun', verbose_name='所属任务')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_items', to='transactions.transaction', verbose_name='关联交易')),
            ],
            options={
                'verbose_name': '对账异常',
                'verbose_name_plural': '对账异常',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('debit', '借'), ('credit', '贷')], max_length=10, verbose_name='方向')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='金额')),
                ('currency', models.CharField(max_length=3, verbose_name='币种')),
                ('entry_type', models.CharField(max_length=40, verbose_name='分录类型')),
                ('external_reference', models.CharField(blank=True, max_length=120, verbose_name='外部引用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='transactions.ledgeraccount', verbose_name='账户')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.payment', verbose_name='支付尝试')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='transactions.refund', verbose_name='退款')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='transactions.transaction', verbose_name='所属交易')),
            ],
            options={
                'verbose_name': '账务分录',
                'verbose_name_plural': '账务分录',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='transactionevent',
            constraint=models.UniqueConstraint(fields=('transaction', 'idempotency_key'), name='uniq_transaction_event_key_per_transaction'),
        ),
    ]
