# Generated by Django 4.2.30 on 2026-04-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('initiated', '已发起'), ('pending', '待支付'), ('requires_action', '待用户操作'), ('paid', '已支付'), ('partially_refunded', '部分退款'), ('refunded', '已退款'), ('failed', '支付失败'), ('cancelled', '已取消')], default='initiated', max_length=20, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='transactionevent',
            name='event_type',
            field=models.CharField(choices=[('initiated', '交易发起'), ('payment_pending', '待支付'), ('payment_requires_action', '待用户操作'), ('payment_paid', '支付成功'), ('payment_failed', '支付失败'), ('payment_cancelled', '支付取消'), ('refund_requested', '退款申请'), ('refund_succeeded', '退款成功'), ('refund_failed', '退款失败')], max_length=40, verbose_name='事件类型'),
        ),
    ]
