# Generated by Django 4.2.30 on 2026-04-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='refund',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='refund',
            name='operator_notes',
            field=models.TextField(blank=True, verbose_name='操作备注'),
        ),
        migrations.AddField(
            model_name='refund',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
    ]
