# Generated by Django 4.2.30 on 2026-04-28 23:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_closed_at_order_internal_notes'),
        ('payments', '0003_payment_transaction'),
        ('transactions', '0003_refund_completed_at_refund_failure_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30, verbose_name='支付渠道')),
                ('settlement_no', models.CharField(max_length=64, unique=True, verbose_name='结算单号')),
                ('currency', models.CharField(max_length=8, verbose_name='币种')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='毛额')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='手续费')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='净额')),
                ('status', models.CharField(choices=[('pending', '待结算'), ('processing', '结算中'), ('settled', '已结算'), ('failed', '结算失败')], default='pending', max_length=20, verbose_name='状态')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结算完成时间')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '结算记录',
                'verbose_name_plural': '结算记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='account_type',
            field=models.CharField(choices=[('asset', '资产'), ('liability', '负债'), ('revenue', '收入'), ('expense', '费用'), ('clearing', '清算')], default='clearing', max_length=20, verbose_name='账户类型'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='currency',
            field=models.CharField(default='USD', max_length=8, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='说明'),
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=64, unique=True, verbose_name='账务流水号')),
                ('kind', models.CharField(choices=[('payment_capture', '支付入账'), ('refund', '退款'), ('fee', '手续费'), ('adjustment', '调账'), ('settlement', '结算'), ('chargeback', '拒付')], max_length=40, verbose_name='账务类型')),
                ('currency', models.CharField(max_length=8, verbose_name='币种')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='毛额')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='净额')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='orders.order', verbose_name='所属订单')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='payments.payment', verbose_name='支付尝试')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='transactions.refund', verbose_name='退款')),
            ],
            options={
                'verbose_name': '账务流水',
                'verbose_name_plural': '账务流水',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=8, verbose_name='币种')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='余额')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='可用余额')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='待结算余额')),
                ('snapshot_at', models.DateTimeField(verbose_name='快照时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='transactions.ledgeraccount', verbose_name='账户')),
            ],
            options={
                'verbose_name': '账户余额快照',
                'verbose_name_plural': '账户余额快照',
                'ordering': ['-snapshot_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='ledger_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='transactions.ledgertransaction', verbose_name='账务流水'),
        ),
    ]
