# Generated by Django 4.2.30 on 2026-04-16 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('easypost', 'EasyPost'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待创建'), ('label_purchased', '已购面单'), ('shipped', '已发货'), ('in_transit', '运输中'), ('delivered', '已送达'), ('exception', '异常'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('external_shipment_id', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('tracking_url', models.URLField(blank=True)),
                ('label_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待创建'), ('label_purchased', '已购面单'), ('shipped', '已发货'), ('in_transit', '运输中'), ('delivered', '已送达'), ('exception', '异常'), ('cancelled', '已取消')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('event_time', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-event_time', '-id'],
            },
        ),
    ]
