# Generated by Django 4.2.30 on 2026-04-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': '发货单', 'verbose_name_plural': '发货单'},
        ),
        migrations.AlterModelOptions(
            name='shipmentevent',
            options={'ordering': ['-event_time', '-id'], 'verbose_name': '物流事件', 'verbose_name_plural': '物流事件'},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送达时间'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='external_shipment_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='第三方发货单号'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='label_url',
            field=models.URLField(blank=True, verbose_name='面单链接'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='所属订单'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='provider',
            field=models.CharField(choices=[('easypost', 'EasyPost'), ('manual', '手动录入')], default='manual', max_length=20, verbose_name='物流渠道'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='原始物流数据'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发货时间'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', '待创建'), ('label_purchased', '已购面单'), ('shipped', '已发货'), ('in_transit', '运输中'), ('delivered', '已送达'), ('exception', '异常'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='物流状态'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='运单号'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(blank=True, verbose_name='物流追踪链接'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='event_time',
            field=models.DateTimeField(verbose_name='事件时间'),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='message',
            field=models.CharField(blank=True, max_length=255, verbose_name='事件说明'),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='事件数据'),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment', verbose_name='所属发货单'),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='status',
            field=models.CharField(choices=[('pending', '待创建'), ('label_purchased', '已购面单'), ('shipped', '已发货'), ('in_transit', '运输中'), ('delivered', '已送达'), ('exception', '异常'), ('cancelled', '已取消')], max_length=20, verbose_name='事件状态'),
        ),
    ]
