# Generated by Django 4.2.30 on 2026-04-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shipment_options_alter_shipmentevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='承运商名称'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='exception_notes',
            field=models.TextField(blank=True, verbose_name='异常备注'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='operator_notes',
            field=models.TextField(blank=True, verbose_name='操作备注'),
        ),
    ]
