# Generated by Django 4.2.30 on 2026-04-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_productfeature_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO 描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='SEO 标题'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, verbose_name='参数说明'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_notes',
            field=models.TextField(blank=True, verbose_name='使用说明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='商品编码（SPU）'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU 编码')),
                ('option_summary', models.CharField(max_length=255, verbose_name='规格组合')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='SKU 图片')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='售价')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='划线价')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本价')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('safety_stock', models.PositiveIntegerField(default=0, verbose_name='安全库存')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品 SKU',
                'verbose_name_plural': '商品 SKU',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='图片')),
                ('image_type', models.CharField(choices=[('primary', '主图'), ('gallery', '轮播图'), ('detail', '详情图')], default='gallery', max_length=20, verbose_name='图片类型')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='替代文本')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('initial_stock', '初始化库存'), ('manual_adjustment', '人工调整'), ('order_deduction', '订单扣减'), ('order_restock', '退款回补')], max_length=30, verbose_name='变动类型')),
                ('quantity_change', models.IntegerField(verbose_name='变动数量')),
                ('before_quantity', models.PositiveIntegerField(verbose_name='变动前库存')),
                ('after_quantity', models.PositiveIntegerField(verbose_name='变动后库存')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.productvariant', verbose_name='关联 SKU')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='类目名称')),
                ('slug', models.SlugField(unique=True, verbose_name='访问标识')),
                ('description', models.TextField(blank=True, verbose_name='类目描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='封面图')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='父类目')),
            ],
            options={
                'verbose_name': '商品类目',
                'verbose_name_plural': '商品类目',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='所属类目'),
        ),
    ]
